alias ls="ls -a"
alias "ll"="ll .."
alias clear="ls"
alias ".."="cd .."
alias "token"="cat ~/token"
alias ls="ls -a"
alias "ll"="ll .."
alias clear="ls"
alias ".."="cd .."
alias "token"="cat ~/token"
alias ls=ls -a
alias ll=ll ..
alias clear=ls
alias ..=cd ..
alias token=cat ~/token
alias ls=ls -a
alias ll=ll ..
alias clear=ls
alias ..=cd ..
alias token=cat ~/token
alias ls="ls -a"
alias "ll"="ll .."
alias clear="ls"
alias ".."="cd .."
alias "token"="cat ~/token"
alias ls=ls -a
alias ll=ls ..
alias clear=ls
alias ..=cd ..
alias token=cat ~/token
